import { News } from '../../types/News';

export default [
  {
    theme: "hello-world",
    title: "Hello, world",
    shortText: "This is a hello world news.",
    fullText: "This is a full version of a news.",
    languageId: "en",
    createdAt: "1",
    commentaries: [
      {
        text: "First commentary",
        rating: 2.0,
        leaveDate: "8",
        publishedBy: null,
      },
      {
        text: "Second commentary",
        rating: 2.0,
        leaveDate: "8",
        publishedBy: null,
      },
      {
        text: "Third commentary",
        rating: 2.0,
        leaveDate: "8",
        publishedBy: null,
      },
      {
        text: "Fourth commentary",
        rating: 2.0,
        leaveDate: "8",
        publishedBy: null,
      },
      {
        text: "Fifth commentary",
        rating: 2.0,
        leaveDate: "8",
        publishedBy: null,
      },
    ],
  },
  {
    theme: "hello-world",
    title: "Привѣт, міре",
    shortText: "То је новина Привѣт, міре.",
    fullText: "То је пълна вѣрсија ової стрåницы.",
    languageId: "nsl",
    createdAt: "2",
    commentaries: [],
  },
  {
    theme: "hello-serbia",
    title: "Hello, Serbia",
    shortText: "This is a hello serbia news.",
    fullText: "This is a full version of a news.",
    languageId: "en",
    createdAt: "3",
    commentaries: [],
  },
  {
    theme: "hello-russia",
    title: "Hello, Russia",
    shortText: "This is a hello russia news.",
    fullText: "This is a full version of a news.",
    languageId: "en",
    createdAt: "4",
    commentaries: [],
  },
  {
    theme: "hello-england",
    title: "Hello, England",
    shortText: "This is a hello england news.",
    fullText: "This is a full version of a news.",
    languageId: "en",
    createdAt: "5",
    commentaries: [],
  },
  {
    theme: "hello-poland",
    title: "Hello, Poland",
    shortText: "This is a hello poland news.",
    fullText: "This is a full version of a news.",
    languageId: "en",
    createdAt: "6",
    commentaries: [],
  },
  {
    theme: "hello-bulgaria",
    title: "Hello, Bulgaria",
    shortText: "This is a hello bulgaria news.",
    fullText: "This is a full version of a news.",
    languageId: "en",
    createdAt: "7",
    commentaries: [],
  },
] as News[];
